name: Coverage

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - run: pnpm i
      - run: pnpm add -D jest-coverage-badges-ng --filter test
      - run: pnpm test:coverage && cd packages/test && pnpm jest-coverage-badges-ng
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/test/coverage
          publish_branch: coverage
