name: Doc

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  doc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Build Doc
        run: pnpm docs:build

      - name: Config
        run: echo 'niuiic.com' > docs/.vitepress/dist/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
          publish_branch: doc
