name: Doc

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  doc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Init
        run: pnpm i

      - name: Build Doc
        run: pnpm build --filter doc

      - name: Config
        run: echo 'fx-flow.niuiic.com' > packages/doc/docs/.vitepress/dist/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/doc/docs/.vitepress/dist
          publish_branch: doc
