name: Lint

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main', 'dev']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: pnpm i
      - run: pnpm lint
      - run: cd packages/core && pnpm lint:test $(cd ../.. && find packages/core/src/pipe packages/core/src/flow -type f)
